### PR TITLE
Tweaked app updates

### LINKED ISSUE #335: Tweak update mechanism
- [x] We need to ensure that auto updater errors get sent to slack
- [x] Use setTimeout instead of setInterval
- [x] The `desktop.updated` config property should contain the new or old version property, which should be compared to the current app version on launch
- [x] If these two versions match, it means that the update installation failed and we need to show a UI banner that allows the user to retry the update by himself

### PR DESCRIPTION
**Pull request by leo**
This PR changes the update mechanism as we've discussed it on Slack (read more in #335). This is how Now Desktop will look after opening when the update installation failed.

screen shot 2017-08-01 at 11 35 27

Fixes #335

### CODE REVIEW

File: main/updates.js [hunk 1]
```diff
@@ -114,35 +116,75 @@ const startBinaryUpdates = () => {
   binaryUpdateTimer(ms('2s'))
 }
 
-const startAppUpdates = () => {
-  autoUpdater.on('error', console.error)
+const checkForUpdates = () => {
+  if (process.env.CONNECTION === 'offline') {
+    setTimeout(checkForUpdates, ms('10s'))
```
Comment (OlliV) [inline main/updates.js]: Shouldn't this be like a super long time instead? If I'm offline it usually means I'll be offline for a very long time and usually running on batter power, e.g. in an ✈️.

Comment (leo) [inline main/updates.js]: @OlliV Great idea! I just bumped it to half an hour (that should be enough, since it will just set the timeout again if you're still offline after that half hour). 😊
